app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import FileField


class FileUploadForm(FlaskForm):
    image = FileField()

app/__init__.py
import logging
import os
from logging.handlers import RotatingFileHandler
from flask import Flask, request, current_app
from config import Config
from flask_bootstrap import Bootstrap
from flask_moment import Moment

bootstrap = Bootstrap()
moment = Moment()

# app creation factory
def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    bootstrap.init_app(app)
    moment.init_app(app)

    # main blueprint
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    # errors blueprint
    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    # logging mechanism
    if not app.debug and not app.testing:
        if not os.path.exists('logs'):
            os.mkdir('logs')
        file_handler = RotatingFileHandler('logs/tabliceo.log', maxBytes=10240, backupCount=10)
        file_handler.setFormatter(
            logging.Formatter('%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('Tabliceo startup')

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
import base64
from flask import request, render_template
from app.main import bp
from app.main.forms import FileUploadForm
from app.main.engine.processing.ExifData import ExifData
from app.main.engine.processing.PlateProcessing import PlateProcessing
from app.main.engine.processing.detection.PlateDetection import get_plate
from app.main.engine.processing.recognition.plate_recognition import segment_characters


@bp.route('/', methods=['GET', 'POST'])
def index():
    form = FileUploadForm()
    if form.validate_on_submit():
        # get image from form, put it through processing;
        image = form.image.data
        image_binary = image.read()

        # exif data processing
        try:
            image_data = ExifData(image_binary)
            image_string = "data:image/jpg;base64," + base64.b64encode(image_binary).decode('ascii')
        except ValueError:
            return render_template('image_error.html', title='Zły format obrazu')

        try:
            LpImg,cor = get_plate(image_binary)
            license_plate = segment_characters(LpImg[0])  
        except AssertionError:
            return render_template('detection_fail.html', title='Błąd wykrywania')

        # put plate number to further processing; processing gets other data from csv
        if len(license_plate) < 7:
            return render_template('detection_fail.html', title='Błąd wykrywania')
        else:
            plate_data = PlateProcessing(license_plate)

        if plate_data.get_plate_type() == -1:
            return render_template('detection_fail.html', title='Błąd wykrywania')
        elif plate_data.get_plate_type() == 0:
            plate_column_1 = "Województwo"
            plate_column_2 = "Powiat"
        else:
            plate_column_1 = "Służba"
            plate_column_2 = "Lokalizacja/rodzaj"

        page_data = [image_string, plate_data.get_render(), plate_data.get_country(), \
                plate_data.get_voivodeship(), plate_data.get_county(), image_data.get_camera(), \
                image_data.get_date(), image_data.get_time(), image_data.get_print_coords(), \
                plate_column_1, plate_column_2, plate_data.get_feature_id(), image_data.get_coords()]
        return render_template('results.html', title='Wyniki', page_data=page_data)
    elif request.method == 'GET':
        return render_template('index.html', title='Strona główna', form=form)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - Tabliceo{% else %}{{ 'Witaj w Tabliceo!' }}{% endif %}
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"
            integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ url_for('main.index') }}"><img
                        src="{{ url_for('static', filename='logo.svg') }}" alt="Tabliceo"></a>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container content">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-info" role="alert">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    <div class="footer"><p>©2021 Tabliceo</p></div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/js/all.min.js" integrity="sha256-MAgcygDRahs+F/Nk5Vz387whB4kSK9NXlDN3w58LLq0=" crossorigin="anonymous"></script>
    {{ super() }}
    {{ moment.include_moment() }}
        {{ moment.lang('pl') }}
{% endblock %}

app/templates/detection_fail.html
{% extends 'base.html' %}

{% block app_content %}
<h1>Błąd wykrywania!</h1>
<hr />
<p>Upewnij się, że zdjęcie jest wyraźne i dobrze pokazuje tablicę rejestracyjną!</p>
<p><a href="{{ url_for('main.index') }}">Wróć na stronę główną</a></p>
{% endblock %}

app/templates/image_error.html
{% extends 'base.html' %}

{% block app_content %}
<h1>Zły format obrazu!</h1>
<hr />
<p>Upewnij się, że zdjęcie jest w formacie JPG lub PNG!</p>
<p><a href="{{ url_for('main.index') }}">Wróć na stronę główną</a></p>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block app_content %}
<div class="mainpage-how">
    <div class="how-cell mt-3 mb-4 bg-light-blue auth-helper">
        <h1>Jak to działa?</h1>
        <hr />

        <div class="row p-3" style="min-height: 350px; display: flex; flex-wrap: wrap; margin-right: -5px; margin-left: -5px;">
            <div class="col-md-4 p-3 bg-pic-1 col-border">
                <div class="col-border-2">
                    <h2>Zdjęcie</h2>
                    <p>Przesłane zdjęcie trafia do nas i jest wnikliwie analizowane.</p>
                </div>
            </div>
            <div class="col-md-4 p-3 bg-pic-2 col-border">
                <div class="col-border-2">
                    <h2>AI</h2>
                    <p>Nasz zaawansowany system sztucznej inteligencji odczytuje ze zdjęcia numer rejestracyjny.</p>
                </div>
            </div>
            <div class="col-md-4 p-3 bg-pic-3 col-border">
                <div class="col-border-2">
                    <h2>Wyniki</h2>
                    <p>Dane ze zdjęcia oraz dane o numerze są prezentowane w mgnieniu oka!</p>
                </div>
            </div>
        </div>
    </div>

    <div class="how-cell how-1">
        <div class="row">
            <div class="col-md-12">
                <h1>Wypróbuj już teraz!</h1>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <p>Kliknij <b>Prześlij</b>, wybierz zdjęcie i to wszystko!</p>
                <p>Tylko pamiętaj, żeby była widoczna na nim tablica.</p>
                <p>Nasz system zajmie się resztą!</p>
            </div>
            <div class="col-md-4">
                <form method="post" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                    <label for="image" class="btn btn-primary btn-lg btn-block blue-button page-button submit-btn">
                        <i class="fas fa-image"></i> Prześlij...
                    </label>
                    <input id="image" type="file"  name="image" style="display: none;" onchange="this.form.submit();"/>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/results.html
{% extends 'base.html' %}

{% block styles %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/mapbox-gl.js') }}"></script>
    <link href="{{ url_for('static', filename='css/mapbox-gl.css') }}" rel="stylesheet" />
{% endblock %}

{% block app_content %}

<h1>Wyniki analizy</h1>
<hr />
<div class="row">
  <div class="col-md-6">
    <div style="background-image: url('{{ page_data[0] }}'); width: 100%; height: 315px; background-position: center; background-size: cover;"></div>
    <h2>Tablica rejestracyjna</h2>
    <hr />
    <img src="{{ page_data[1] }}" style="width: 100%;" />
    <table class="table" style="width: 100%; border-radius: 10px; background-color: rgba(17, 103, 177, 0.3);
    margin-top: 10px;   border-collapse: collapse;   border-style: hidden;">
      <tr style="border-bottom: 2px solid #1167B1;">
          <th style="width: 30%; text-align: right; border-right: 2px solid #1167B1;">Kraj</th>
          <td>{{ page_data[2] }}</td>
      </tr>
      <tr style="border-bottom: 2px solid #1167B1;">
          <th style="width: 30%; text-align: right; border-right: 2px solid #1167B1;">{{ page_data[9] }}</th>
          <td>{{ page_data[3] }}</td>
      </tr>
      <tr>
          <th style="width: 30%; text-align: right; border-right: 2px solid #1167B1;">{{ page_data[10] }}</th>
          <td>{{ page_data[4] }}</td>
      </tr>
    </table>
  </div>
  <div class="col-md-6">
    <h2>Zdjęcie</h2>
    <hr />
    <table class="table" style="width: 100%; border-radius: 10px; background-color: rgba(17, 103, 177, 0.3);
    margin-top: 10px;   border-collapse: collapse;   border-style: hidden;">
      <tr style="border-bottom: 2px solid #1167B1;">
          <th style="width: 30%; text-align: right; border-right: 2px solid #1167B1;">Aparat</th>
          <td>{{ page_data[5] }}</td>
      </tr>
      <tr style="border-bottom: 2px solid #1167B1;">
          <th style="width: 30%; text-align: right; border-right: 2px solid #1167B1;">Data</th>
          <td>{{ page_data[6] }}</td>
      </tr>
      <tr>
          <th style="width: 30%; text-align: right; border-right: 2px solid #1167B1;">Godzina</th>
          <td>{{ page_data[7] }}</td>
      </tr>
    </table>
    <h2>Lokalizacja</h2>
    <hr />
    <table class="table" style="width: 100%; border-radius: 10px; background-color: rgba(17, 103, 177, 0.3);
    margin-top: 10px;   border-collapse: collapse;   border-style: hidden;">
      <tr>
          <th style="width: 30%; text-align: right; border-right: 2px solid #1167B1;">Współrzędne</th>
          <td>{{ page_data[8] }}</td>
      </tr>
    </table>
    <div id="map"></div>
  </div>
</div>

<script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
<script src="{{ url_for('static', filename='js/map.js') }}"></script>
<script type="text/javascript">
  map.on('style.load', () => {
    const waiting = () => {
      if (!map.isStyleLoaded()) {
        setTimeout(waiting, 200);
      } else {
        colourFeature({{page_data[11]}});
        createMarker({{page_data[12][0]}}, {{page_data[12][1]}});
      }
    };
    waiting();
  });
</script>
{% endblock %}